### ISSUE TITLE
Enable addition of more content for Experience/Side event (Front-End Version)

### ISSUE THREAD

**Issue by Donald-Paul** [Studio19/EventManagement#37]

**Comment by Donald-Paul** [comment]
I have broken down the process of fetching the parameters from the database in commit 3f03d4c165c6905e187504e5f2480cf46facebb0 All that is remaining is to fill html and javascript if required. @brompo

**Comment by brompo** [comment]
Displayed content from the extra details on the side events, still yet to work on pictures. 51a4c366e4eb3446d252b8bf0aa2c61863222f50
