### ISSUE TITLE
Create a Mechanism to Add People, with Tickets that you don't have to pay for

### ISSUE THREAD

**Issue by brompo** [Studio19/EventManagement#40]
This is very important for the migration of people, from the old system to the New System.

**Comment by Donald-Paul** [comment]
may need to verify how it works in commit d59067b569c516c3b0303c87e245169504a827c2

**Comment by Donald-Paul** [comment]
reinforced security measure for ensuring there is no compromise before skipping the payment in commit b1cc2fb80b89c6a49f99a8fd0fa6de913f38132c
